### ISSUE TITLE
Add ability to test notebooks and some nb outputs

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#132]
This includes:
1. add papermill to execute notebooks
2. add scrapbook to test one output in a notebook

**Comment by imatiach-msft** [comment]
added notebook tests, scrapbook and cell validation
https://github.com/interpretml/interpret-community/pull/155
https://github.com/interpretml/interpret-community/pull/157
https://github.com/interpretml/interpret-community/pull/158
