### ISSUE TITLE
Way to view the dashboard locally on browser

### ISSUE THREAD

**Issue by anujanegi** [interpretml/interpret-community#168]
Is there a way to get the url to open the dashboard on the browser locally? The previous interpret repo has a show_link functionality that does this.

How can this be done for the ExplanationDashboard function?

**Comment by rihorn2** [comment]
You can view the dashboard in a separate tab after starting it in the notebook. The default route is http://127.0.0.1:5000/1 where the /1 is for the first model/dashboard viewed, and subsequent views will increment this. You can check what the route is by opening dev-tools (F12) and going to the network tab. rerun the explanation dashboard cell with the network tab open and you will see the local route to use.

Thank you for laying out these use cases, I agree that surfacing a button to easily navigate to a full tab view makes the product better.
Thanks,
Brandon

**Comment by anujanegi** [comment]
Thanks Brandon for your quick and insightful reply.
