### ISSUE TITLE
ExplanationDashboard fails trying to connect to IPv6

### ISSUE THREAD

**Issue by scottcode** [interpretml/interpret-community#227]
**Describe the bug**
On a system that doesn't support or doesn't allow opening ports using IPv6, creating an `ExplanationDashboard` fails, saying that it couldn't find/open any available port. 

**To Reproduce**
1. Use a system that doesn't support or allow IPv6 to refer to localhost
2. Instantiate the `ExplanationDashboard

**Expected behavior**
I expected the dashboard to initialize, including creating and running the Flask app in the backend. 

**Environment:**
 - OS: RHEL 7.7
 - Browser: Chrome
 - `interpret_community` version 0.10.2

**Cause**
Identified the location causing the problem as the `_local_port_available` method (full reference: `interpret_community.widget.explanation_dashboard.ExplanationDashboard.DashboardService._local_port_available`. It tries both the specified IP address as well as the IPv6 version of `localhost`. Without the IPv6 check it works on my server. 

I recommend removing that check, because it unnecessarily bypasses the user-specified IP. If the user wants to use an IPv6 address, they can specify so explicitly.

**Comment by imatiach-msft** [comment]
seems reasonable to me, @rihorn2 ?

**Comment by imatiach-msft** [comment]
closing as PR with fix has been merged
