### ISSUE TITLE
No Dashboard output

### ISSUE THREAD

**Issue by karthikreddykuna** [interpretml/interpret-community#275]
Dashboard output is not generating when I generate global explanations and dashboards in the same code cell. 

![image](https://user-images.githubusercontent.com/55387103/86088122-b7731780-ba73-11ea-812b-f5f72ddb3e31.png)

global_explanation = explainer.explain_global(x_test)
ExplanationDashboard(global_explanation, model, datasetX=x_test)

Can you please let me know how to extract the dashboard without executing in two separate cells.

**Comment by imatiach-msft** [comment]
@karthikreddykuna  what environment are you running in (eg local notebook, databricks, or azure notebooks)?  Just to confirm, do you see the dashboard if it is run in its own cell?

**Comment by imatiach-msft** [comment]
The widget code is very different since July 2020, so closing this issue as it's probably not relevant anymore.  Please feel free to reopen if you are still seeing this issue or create a new one with more details.
