### ISSUE TITLE
Documentation for BaseExplanation class?

### ISSUE THREAD

**Issue by swanderz** [interpretml/interpret-community#317]
**Is your feature request related to a problem? Please describe.**
Per this issue: https://github.com/Azure/MachineLearningNotebooks/issues/1125
> Well many users may not know what a BaseExplanation object is and likely isn't documented elsewhere. In similar documentation the BaseExplanation would contain a link, to another place where BaseExplanation is explained. Upload model requires a BaseExplanation, download model returns a BaseExplanation. But the BaseExplanation object itself is undocumented.
> When you look into the BaseExplanation object itself, it has a lot of properties and methods. I would recommend creating a separate doc page about that object so that a user could use the methods of that object. This would make it easier to be certain that a user's application accomplishes what they assume it will do.

**Describe the solution you'd like**
> Clear documentation of the class's method and attributes

**Describe alternatives you've considered**
- Asking the product group directly
- Looking directly at [the source code](https://github.com/interpretml/interpret-community/blob/master/python/interpret_community/explanation/explanation.py)

**Additional context**
the [ExplanationClient class page](https://docs.microsoft.com/en-us/python/api/azureml-contrib-interpret/azureml.contrib.interpret.explanation.explanation_client.explanationclient?view=azure-ml-py) says that `.download_model_explanation()` returns a `BaseExplanation` but there's no page for that class.

**Comment by swanderz** [comment]
cc: @imatiach-msft

**Comment by imatiach-msft** [comment]
@swanderz the BaseExplanation class is located here:
https://github.com/interpretml/interpret-community/blob/master/python/interpret_community/explanation/explanation.py#L29

There is already thorough documentation here (and has been for a long time):
https://interpret-community.readthedocs.io/en/latest/api_reference/interpret_community.explanation.explanation.html#interpret_community.explanation.explanation.BaseExplanation

Hope that helps resolve this issue!

**Comment by imatiach-msft** [comment]
closing this issue as there is already documentation for this class

**Comment by swanderz** [comment]
the issue is that it isn't available on the main SDK docs site. See the section for `ExplanationClient.download_model()` how does a user find out more about `BaseExplainer` from that location? There's no page for `BaseExplainer` available, regardless of whether it exists.

<img width="158" alt="image" src="https://user-images.githubusercontent.com/8158673/93385416-1a767e00-f81b-11ea-9767-d88f64ac1a9e.png">

**Comment by imatiach-msft** [comment]
@swanderz sure, how can I fix this then?  I don't see any way to reference interpret community doc from the azure doc.

**Comment by swanderz** [comment]
@j-martens to the rescue?!

**Comment by imatiach-msft** [comment]
@swanderz @j-martens can this issue be closed?  This looks like an issue with the way the doc generation is done on this page:
https://docs.microsoft.com/en-us/python/api/azureml-interpret/azureml.interpret?view=azure-ml-py
It looks like interpret-community package is not included when doc generation is done via sphinx.

**Comment by swanderz** [comment]
@imatiach-msft totally fine w/ closing this. I only opened this issue because https://github.com/Azure/MachineLearningNotebooks/issues/1125 was closed without a resolution.
