### ISSUE TITLE
Question about interpret-dashboard package on npm

### ISSUE THREAD

**Issue by harupy** [interpretml/interpret-community#330]
Is there any plan to open source the interpret-dashboard package on npm: https://www.npmjs.com/package/interpret-dashboard?

**Comment by imatiach-msft** [comment]
hi @harupy , yes, this was open-sourced under interpret-community but it is moving to a common responsible AI UX repo, so it is easier to mix/match components, share code across several responsible AI projects and debug UX issues.  It was removed in this very recent commit:
https://github.com/interpretml/interpret-community/commit/7e29ca840d59fd495ac8d43e299dbe97755aaa85
The new repo containing that deleted UX code with some updates will soon be open sourced as well.
