### ISSUE TITLE
Save the explainer

### ISSUE THREAD

**Issue by pathikchamaria** [interpretml/interpret-community#342]
It would be great if the Explainer generated can be saved so as to be able to reuse later on and not wait for it to be created once again. It would be especially helpful in cases when the inference time is larger for the model.

**Comment by pathikchamaria** [comment]
@imatiach-msft any comments on this?

**Comment by gaugup** [comment]
Hi,

Thanks for the suggestion. Some of the solution that come to mind are following:-

1. You could save the explainer using pickle and rehydrate it from the pickle file.
2. If you are using AzureML, then azureml-interpret supports scoring explainer using which you can persist an explainer and then use it at inference time.

Thanks

**Comment by rodrigovssp** [comment]
#UP


Em qui., 12 de nov. de 2020 às 19:53, gaugup <notifications@github.com>
escreveu:

**Comment by pathikchamaria** [comment]
Hi @gaugup ,

I tried pickle but it did not work. It is giving some error on thread based objects.  Any concrete steps on how to do it?

**Comment by gaugup** [comment]
Hi @pathikchamaria,

I saw that pickle of MimicExplainer doesn't work. It might be due to the logger (guess at this point). I think we may have to tinker with the __getstate__() and __setstate__() functions of the explainer. Which explainer in interpret-community are you looking to persist? 

Regards,

**Comment by gaugup** [comment]
Hi @pathikchamaria,

I have created a sample PR https://github.com/interpretml/interpret-community/pull/344 for pickling and unpickling the MimicExplainer using LightGBM/Linear surrogate models. The PR also has tests to pickle and unpickle the mimic explainer. 

Let me know if this PR serves as an example. If it does we can try to add the same logic to other explainers.

Regards,

**Comment by pathikchamaria** [comment]
Hi @gaugup,

Thanks for the quick response. Yeah, it would work, my only concern is that in the test you did not try explaining from unpickled explainer. I hope that you would have already tried. 

Just a thought if we could add same logic to other explainers also.

**Comment by pathikchamaria** [comment]
@gaugup Is it possible to share a timeline on this particular feature request?

**Comment by gaugup** [comment]
@pathikchamaria at this moment we can only pickle and unpickle the MimicExplainer and its surrogate models. I soke to @imatiach-msft  about pickling of other explainers and he mentioned that it might be difficult to pickle shap explainers as these are not as straightforward. Is that ok?

**Comment by pathikchamaria** [comment]
Shap explainers by themselves are pickable I am not sure why you would face issue.  For now, even MimicExplaners would be good.

**Comment by gaugup** [comment]
Thanks for confirming. I think we are able to pickle couple of surrogate models in the PR https://github.com/interpretml/interpret-community/pull/344. I will add code for the remaining surrogate models.

**Comment by gaugup** [comment]
@pathikchamaria the PR #344 is updated to pickle all surrogate models in MimicExplainer. You could take a look?

**Comment by pathikchamaria** [comment]
Yes, it works. I have also tried it.

**Comment by gaugup** [comment]
Thanks @pathikchamaria . I have merged the PR https://github.com/interpretml/interpret-community/pull/344. Please feel free to close the issue if your query is addressed in this issue.

**Comment by pathikchamaria** [comment]
Sure, shall close the issue. Shall wait for new release.
