### ISSUE TITLE
Issue with importing explainers and models

### ISSUE THREAD

**Issue by rohitsuresh1993** [interpretml/interpret-community#349]
Hello,
I have issues importing explainer and models on my local machine. I have followed all the installation steps as listed in this repo.

I am trying to use the library in a jupyter notebook in VSCode (Python 3)

When I execute 
`from interpret.ext.blackbox import MimicExplainer`
I get the following error
`ImportError: cannot import name 'MimicExplainer' from 'interpret.ext.blackbox' (C:\Users<username>\AppData\Roaming\Python\Python37\site-packages\interpret\ext\blackbox\__init__.py)`

The following command executes
`from interpret.ext.blackbox import *`
But when I try using the MimicExplainer, it throws this error
`NameError: name 'MimicExplainer' is not defined`

**Desktop:**
 - Windows 10

**Comment by gaugup** [comment]
Hi @rohitsuresh1993,

What version of interpret-community and interpret-core do you have installed in your python environment? Could you try importing "from interpret_community.mimic.mimic_explainer import MimicExplainer" in your python environment?

Regards,

**Comment by rohitsuresh1993** [comment]
Hi @gaugup ,

Thanks! That import command works!

These are my versions:
interpret-community    0.15.4
interpret-core    0.2.1

**Comment by me-shubh** [comment]
Throwing me the same error,and Mimic Explainer is working, but what about - 

ImportError: cannot import name 'LinearExplaiableModel' from 'interpret.ext.glassbox

**Comment by imatiach-msft** [comment]
@me-shubh there is no "LinearExplaiableModel", it is "LinearExplainableModel", you are missing an n in the name.  Might that fix the issue?  Otherwise try the interpret_community namespace import instead of the extension.

**Comment by me-shubh** [comment]
> @me-shubh there is no "LinearExplaiableModel", it is "LinearExplainableModel", you are missing an n in the name. Might that fix the issue? Otherwise try the interpret_community namespace import instead of the extension.

Yes Sorry I was talking about LinearExplainableModel only.
