### ISSUE TITLE
AttributeError: type object 'PFIExplainer' has no attribute 'explainable_model_type'

### ISSUE THREAD

**Issue by ibobak** [interpretml/interpret-community#390]
I'm running this code
```
explainer = MimicExplainer(model, 
                           X_test, 
                           PFIExplainer, 
                           augment_data=True, 
                           max_num_of_augmentations=10, 
                           categorical_features=CAT_FEATURES,
                           features=USE_FEATURES)
```
And I am facing with this bug:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-a93f85c89153> in <module>
----> 1 explainer = MimicExplainer(model, 
      2                            X_test,
      3                            PFIExplainer,
      4                            augment_data=True,
      5                            max_num_of_augmentations=10,

/opt/anaconda3/envs/lto/lib/python3.8/site-packages/interpret_community/dataset/decorator.py in init_wrapper(self, model, initialization_examples, *args, **kwargs)
     40     @wraps(init_func)
     41     def init_wrapper(self, model, initialization_examples, *args, **kwargs):
---> 42         return init_func(self, model, wrap_dataset(initialization_examples), *args, **kwargs)
     43     return init_wrapper

/opt/anaconda3/envs/lto/lib/python3.8/site-packages/interpret_community/mimic/mimic_explainer.py in __init__(self, model, initialization_examples, explainable_model, explainable_model_args, is_function, augment_data, max_num_of_augmentations, explain_subset, features, classes, transformations, allow_all_transformations, shap_values_output, categorical_features, model_task, reset_index, **kwargs)
    286 
    287         # If model is a linear model or isn't able to handle categoricals, one-hot-encode categoricals
--> 288         is_tree_model = explainable_model.explainable_model_type == ExplainableModelType.TREE_EXPLAINABLE_MODEL_TYPE
    289         if is_tree_model and self._supports_categoricals(explainable_model):
    290             # Index the categorical string columns for training data

AttributeError: type object 'PFIExplainer' has no attribute 'explainable_model_type'
```

**Comment by imatiach-msft** [comment]
hi @ibobak , the mimic explainer takes an explainable surrogate model, not another explainer.  You shouldn't pass PFIExplainer as the surrogate model to MimicExplainer.  Instead, you can pass any of these:

from interpret.ext.glassbox import LGBMExplainableModel
from interpret.ext.glassbox import LinearExplainableModel
from interpret.ext.glassbox import SGDExplainableModel
from interpret.ext.glassbox import DecisionTreeExplainableModel

please see docs for model module:
https://interpret-community.readthedocs.io/en/latest/api_reference/interpret_community.mimic.models.html

**Comment by imatiach-msft** [comment]
I think we can add a better exception message here though.  Also, I think there is still a bug with explainable_model_type, it's actually a static method currently not a property:

https://github.com/interpretml/interpret-community/blob/master/python/interpret_community/mimic/models/explainable_model.py#L80

let me send a PR to fix this

**Comment by imatiach-msft** [comment]
did you get this error when running a surrogate model as well, instead of PFIExplainer (which is not a surrogate model and shouldn't be passed into MimicExplainer)?

**Comment by imatiach-msft** [comment]
it looks like you wouldn't get an error but the underlying explainer might not treat the categoricals correctly even if you did pass the correct surrogate model

**Comment by imatiach-msft** [comment]
@ibobak did you try passing in a surrogate model instead of PFIExplainer?  If it worked, is it ok to close this issue?  Thank you!

**Comment by imatiach-msft** [comment]
gentle ping @ibobak

**Comment by imatiach-msft** [comment]
closing this issue as it was resolved
