### ISSUE TITLE
Issue due to pytorch not being installed needs a try-catch

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#40]
**Describe the bug**
When setting up pfi in /notebooks/explain-regression-local.ipynb notebook, an error occurs when using PFI when pytorch is not installed.

**To Reproduce**
run nb.

**Screenshots**
![image](https://user-images.githubusercontent.com/6098674/67215365-50cf3180-f3ef-11e9-9195-d00bd01f32b1.png)

**Additional context**

**Comment by imatiach-msft** [comment]
closing as issue has been fixed
