### ISSUE TITLE
TabularExplainer doesn't work for some data transformer

### ISSUE THREAD

**Issue by heimengqi** [interpretml/interpret-community#403]
I am working with the employee attrition dataset and I realized that if I change the data transformation a bit (e.g. make the `OneHotEncoder()` drops the first column), I will get a dimension mismatch error when call `explainer.explain_global(x_test)`, I guess there is a bug when internally transform the input x_train and x_test, which are raw features? Below is the code snippet:

```
from sklearn.compose import ColumnTransformer

# We create the preprocessing pipelines for both numeric and categorical data.
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='error',drop='first'))])

transformations = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical),
        ('cat', categorical_transformer, categorical)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', transformations),
                      ('classifier', LGBMClassifier())])

clf.fit(x_train, y_train)

explainer = TabularExplainer(clf.steps[-1][1], 
                             initialization_examples=x_train, 
                             features=attritionXData.columns, 
                             classes=['Leaving', 'Staying'], 
                             transformations=transformations)

global_explanation = explainer.explain_global(x_test)
```

It works well with default `OneHotEncoder` without dropping the first column, I tested it on both version 0.17.2 and 0.16.0 (if upgrade azureml-contrib-interpret, will downgrade this package) 

Let me know if I am doing something wrong.

**Comment by imatiach-msft** [comment]
@heimengqi azureml-contrib-interpret is deprecated/removed, please use azureml-interpret package instead (what specifically are you using from that package?).

**Comment by imatiach-msft** [comment]
@heimengqi 
"if I change the data transformation a bit (e.g. make the OneHotEncoder() drops the first column), I will get a dimension mismatch error when call explainer.explain_global(x_test)"
it looks like this mapper for OneHotEncoder needs to be updated to support this "drop" case:

https://github.com/interpretml/interpret-community/blob/master/python/interpret_community/_internal/raw_explain/feature_mappers.py#L204

**Comment by imatiach-msft** [comment]
@heimengqi are you blocked on this issue right now? it should be a simple feature to add.  otherwise you can create a custom feature mapper, but it might be easier to just update the code in interpret-community for this supported transformation.

**Comment by heimengqi** [comment]
```
%pip uninstall interpret-community -y
%pip install --upgrade interpret-community[visualization]
%pip install --upgrade azureml-interpret
%pip install --upgrade azureml-contrib-interpret
%pip install econml
```
Chris shared a notebook with me with these dependence update at the beginning, maybe it's out of date. I am also a bit confused about those different packages, they all look similar. In order to run `TabularExplainer`, only install  `interpret-community` is enough now?

**Comment by imatiach-msft** [comment]
@heimengqi yes, you only need interpret-community for TabularExplainer.  If you want to upload/download explanations, create a scoring explainer or use the MimicWrapper you can use azureml-interpret for that.

**Comment by imatiach-msft** [comment]
@heimengqi you shouldn't need azureml-contrib-interpret package for anything anymore.  It was deprecated almost a year ago and removed a couple months ago (it's no longer updated on pypi).

**Comment by heimengqi** [comment]
Cool thanks! Not completely blocked,  I could see alternatives for now, but it would be great if we support this eventually.

**Comment by imatiach-msft** [comment]
closing issue as fix has been merged
