### ISSUE TITLE
 'ExplainableBoostingClassifier' object has no attribute 'feature_groups_'

### ISSUE THREAD

**Issue by Vptel** [interpretml/interpret-community#407]
Hi,

I recently tried to score my model and build the explainable global wrapper but keep getting the error AttributeError: 'ExplainableBoostingClassifier' object has no attribute 'feature_groups_'. 

Is anyone able to help me understand this issue?  
![image](https://user-images.githubusercontent.com/18105503/117317781-ba078000-ae81-11eb-897a-56bc04004375.png)

![image](https://user-images.githubusercontent.com/18105503/117317819-c4297e80-ae81-11eb-8818-e351c470126b.png)

**Comment by imatiach-msft** [comment]
closing this, please re-open this issue in https://github.com/interpretml/interpret thanks!

**Comment by imatiach-msft** [comment]
@Vptel please create issue in https://github.com/interpretml/interpret repository
