### ISSUE TITLE
Interpretability on AutoML models

### ISSUE THREAD

**Issue by lucazav** [interpretml/interpret-community#449]
I can't find a notebook with an example of an interpretability dashboard done on an AutoML model [here](https://github.com/interpretml/interpret-community/tree/master/notebooks).
Is it possible to add one, please?

**Comment by imatiach-msft** [comment]
hi @lucazav , you can find the documentation here on how to run the interpretability dashboard on an AzureML AutoML model:
https://docs.microsoft.com/en-us/azure/machine-learning/how-to-machine-learning-interpretability-automl#:~:text=Automated%20ML%20helps%20you%20understand%20feature%20importance%20of,interpretability.%20In%20this%20article%2C%20you%20learn%20how%20to%3A

This is an OSS repository not tied to AzureML or any platform so such a notebook shouldn't live here in the interpret-community OSS repository.  Closing this issue.
