### ISSUE TITLE
Score of the surrogate model

### ISSUE THREAD

**Issue by garyee** [interpretml/interpret-community#452]
**Is your feature request related to a problem? Please describe.**
Is there a way to compute a score ([like R-squared](https://christophm.github.io/interpretable-ml-book/global.html#theory-4)) for the output of the surrogate model?
I would like to know if I can trust the explanations given by the surrogate or if I should be careful.

**Describe the solution you'd like**
It would be great if there would be a score property in GlobalExplanation and a parameter when creating the explainer to pass in a custom score function.

**Comment by imatiach-msft** [comment]
@garyee great point.  It's already possible to get the replication score here:
https://github.com/interpretml/interpret-community/blob/9dbb33e259bcbe7ad3046f73efd6950d53976b61/python/interpret_community/mimic/mimic_explainer.py#L751
However this needs to be turned into a public API and integrated with our explanation and dashboard, so it's always shown for explanations from mimic explainer.

**Comment by gaugup** [comment]
@garyee , how do you plan to use this score? Like comparing the various surrogate models used with MimicExplainer? If that is the case, could you try the above private function to see if this helps your scenario?

As Ilya mentioned we could turn this into a public function and add to an interpret notebook.

Regards,

**Comment by gaugup** [comment]
@garyee, I have created https://github.com/interpretml/interpret-community/pull/495 to make the function _get_surrogate_model_replication_measure() public. I will also add the usage of this function to one of the notebooks.

Let me know if you would need anything else to be done for this function.

Regards,

**Comment by SamiurRahman1** [comment]
Hi! has the function been used in any of the notebooks yet? :)

**Comment by gaugup** [comment]
@SamiurRahman1, @garyee , there a new notebook in the PR https://github.com/interpretml/interpret-community/pull/506 which uses the above function. If you plan to use the notebook in the PR, then do let us know if you would want to add anything to the notebook.

Regards,
