### ISSUE TITLE
change wording in nb Explain-regression-local

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#50]
**Describe the bug**
When running PFI, comment in nb says:
# Note: PFIExplainer does not support local explanations

Should change to say:
Do not run this cell if using PFIExplainer

**To Reproduce**
Run notebook

**Expected behavior**
More detailed error.

**Screenshots**
![image](https://user-images.githubusercontent.com/6098674/67314700-2e164900-f4d3-11e9-9f60-7a12c823581b.png)

**Comment by bethz** [comment]
And add more comments to other cells that will not run successfully if using PFI

**Comment by imatiach-msft** [comment]
fixed with merged PR https://github.com/interpretml/interpret-community/pull/99
