### ISSUE TITLE
Question. How is the global explanation measured?

### ISSUE THREAD

**Issue by SamiurRahman1** [interpretml/interpret-community#501]
Hi! I understand how the local feature importance are being created. But i don't exactly understand, how the global model is interpreted. Do you aggregate all the local feature importance to get the global feature importance? Or is it calculated independently?

Thanks

**Comment by imatiach-msft** [comment]
hi @SamiurRahman1 yes, it depends on the interpretability method.  For most of the ones that compute local importances (lime, shap-based ones like KernelExplainer, TreeExplainer and LinearExplainer) we average.  For some, like permutation feature importance, we actually compute the global importance values.  For the mimic explainer, which is the one with most usage in this repository (and most development effort), we actually have both options - if you pass an evaluation dataset, it will average local importance values by computing ```mean(abs(local_importances))```, and if you don't pass any dataset it will just get the importances on the model - so for a lightgbm model it will be:

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier.feature_importances_

there are some more documents on that parameter here:
https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/sklearn.py#L445
and some article I found linked here:
https://medium.com/the-artificial-impostor/feature-importance-measures-for-tree-models-part-i-47f187c1a2c3

I think it would be useful to put all of this info on the generated docs website, which currently only has API info.
https://interpret-community.readthedocs.io/en/latest/index.html

**Comment by SamiurRahman1** [comment]
Hi! thank you so much for your detailed explanation. So, i understood that if i provide an evaluation dataset(i.e. `global_explanation = explainer.explain_global(_**X_test**_)`), then the mimic explainer would average the local importances and derive the global importance. and on the other hand,  `global_explanation = explainer.explain_global()` would provide only the global importance, which is calculated through either "_split_" or "_gain_" method. is my assumption correct? :)

**Comment by imatiach-msft** [comment]
@SamiurRahman1 yes, I think that's a good summary of the MimicExplainer with LightGBM surrogate model specifically

**Comment by SamiurRahman1** [comment]
thanks. is it safe to assume that we are using the "_split_" method in this framework?

**Comment by imatiach-msft** [comment]
@SamiurRahman1 
yes, the default is split:
![image](https://user-images.githubusercontent.com/24683184/153273054-db35729a-42d4-4da3-b3bf-f02001718c92.png)
you can change it by passing a different parameter for importance_type on the surrogate_model_args to mimic explainer

**Comment by imatiach-msft** [comment]
https://github.com/interpretml/interpret-community/blob/master/python/interpret_community/mimic/mimic_explainer.py#L159

explainable_model_args

**Comment by SamiurRahman1** [comment]
i got my answer! thanks a lot for all the help :)
