### ISSUE TITLE
Calculate r2_score for PFIExplainer

### ISSUE THREAD

**Issue by SamiurRahman1** [interpretml/interpret-community#508]
I would like to calculate the r2 score of my PFIExplainer method. As much as i understand, it should be done like this:
`explainer_pfie = PFIExplainer(myModel, is_function = False, model_task = model_task, metric= 'r2_score', features=X_train.columns)`. But i am not completely sure if i am actually doing it correctly.  When i run `explainer_pfie = PFIExplainer(myModel, is_function = False, model_task = model_task, features=X_train.columns)` and then run `explainer_pfie.get_surrogate_model_replication_measure(training_data=X_train.values)` , i get the error `'PFIExplainer' object has no attribute 'get_surrogate_model_replication_measure'` . But when i use the mimic explainer, it works. How can i get the r2 score for PFIExplainer?

**Comment by gaugup** [comment]
`PFIExplainer` doesn't implement `get_surrogate_model_replication_measure()`. Does `PFIExplainer` train a surrogate model like `MimicExplainer`?

Regards,

**Comment by SamiurRahman1** [comment]
good point. but there is still a way to calculate the r2 score for PFIE, right?

**Comment by gaugup** [comment]
Which r2_score are you referring to? From the code I just see the r2_score computed between the true_labels and the predicted label from the shuffled dataset when you pass true_labels during the explain_global() function. Is that what you are looking for?

Regards,

**Comment by imatiach-msft** [comment]
@SamiurRahman1 you are doing it correctly, there is no surrogate model for PFI explainer so this shouldn't work:
get_surrogate_model_replication_measure
However, how you are specifying the r2_score is correct.  As @gaugup mentioned, it calculates the r2 score between the true and predicted labels.

**Comment by SamiurRahman1** [comment]
yea, i realised my misconception. i was talking about calculating r2 score to to understand how good the explainer model explains the black-box model. but PFIE does not use a surrogate model, so there can't be an evaluation score for that.

**Comment by gaugup** [comment]
Can you close this issue if your query has been ansswered?

Regards,
