### ISSUE TITLE
Code Formatting Standards

### ISSUE THREAD

**Issue by vin-nag** [interpretml/interpret-community#521]
Hi,

I was looking to contribute to this repo. I understand that we need to agree to the DCO as a requirement. I was wondering if there were any particular code formatting styles recommended/enforced for this project?

**Comment by imatiach-msft** [comment]
hi @vin-nag contributions are welcome!
"I was wondering if there were any particular code formatting styles recommended/enforced for this project?"
Yes, you will need to run flake8 and isort, see:

https://github.com/interpretml/interpret-community/blob/813be7ae1705ab6c13434ad6a22152785a783153/.github/workflows/python-linting.yml

I usually run flake8 at the root level:
```
flake8 --max-line-length=119
```
It will tell you what style change will need to be made.

For isort, it will actually auto-correct the code.  To see the issues, you just need to run:

```
isort . -c
```

To autocorrect the issues, you can remove the -c parameter:

```
isort .
```

It will auto-correct the imports for you.

If you have any other style suggestions please let us know.

**Comment by imatiach-msft** [comment]
closed with PR https://github.com/interpretml/interpret-community/pull/522 where I added a contributing guide to the website

**Comment by imatiach-msft** [comment]
see https://interpret-community.readthedocs.io/en/latest/contributing.html#

**Comment by imatiach-msft** [comment]
@vin-nag did you have any other questions about making contributions to this repository?  Did you encounter any issues when trying to make a contribution?
