### ISSUE TITLE
nb warnings: simple-feature-transformation-exp nb warning when training svm

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#54]
**Describe the bug**
When training an SVM, a deprecation warning occurs.

**To Reproduce**
1. run the nb
2. train step has warning

**Expected behavior**

**Screenshots**
Train a SVM classification model, which you want to explain:

![image](https://user-images.githubusercontent.com/6098674/67418656-3638bc00-f599-11e9-8228-6c3710878c2d.png)

**Desktop (please complete the following information):**
Edge

**Additional context**

**Comment by imatiach-msft** [comment]
closing as this issue seems to already be fixed with @bethz 's changes
