### ISSUE TITLE
nb warnings: simple-feature-transformation-exp nb tabular explainer

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#55]
**Describe the bug**
simple-feature-transformation-exp nb during tabular explainer use

**To Reproduce**
1. run notebook
2. warning occurs during cell to explain model using tabularexplainer

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6098674/67418766-66805a80-f599-11e9-8182-0c3c1a3ea9c2.png)

**Desktop (please complete the following information):**
Edge

**Additional context**

**Comment by imatiach-msft** [comment]
fix was merged, closing issue
