### ISSUE TITLE
nb warnings: simple-feature-transformation-exp nb warning when doing global explaining using local comp

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#56]
**Describe the bug**
warning in simple-feature-transformation-exp

**To Reproduce**
1. run nb
2. try global explainer with local component'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6098674/67419128-1b1a7c00-f59a-11e9-961d-6296023aed26.png)

**Desktop (please complete the following information):**
Edge

**Additional context**

**Comment by imatiach-msft** [comment]
this warning doesn't appear anymore, hence closing issue
