### ISSUE TITLE
nb warnings: simple-feature-transformation-exp nb warning for num_features for local explainer for shap

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#57]
**Describe the bug**
simple-feature-transformation-exp nb warning

**To Reproduce**
1. run nb
2. run local explainer

**Expected behavior**
no warning

**Screenshots**
![image](https://user-images.githubusercontent.com/6098674/67419477-c4fa0880-f59a-11e9-83ba-261e9015327c.png)

**Additional context**

**Comment by imatiach-msft** [comment]
closing as this warning doesn't appear anymore
