### ISSUE TITLE
skipped test: test_explain_model_lightgbm_binary

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#60]
**Describe the bug**
This is a reminder that this test is skipped for now.
Message from test:
skipping test until shap TreeExplainer for lightgbm binary classifier fixed

**To Reproduce**
1. Go to devops
2. Check nightly log

**Expected behavior**
test would run

**Screenshots**
![image](https://user-images.githubusercontent.com/6098674/67493186-853c2b00-f645-11e9-85fc-5266575dc916.png)

**Additional context**

**Comment by imatiach-msft** [comment]
fixed as part of PR:
https://github.com/fairlearn/fairlearn
