### ISSUE TITLE
lightgbm tests failing for mac build pipeline

### ISSUE THREAD

**Issue by wamartin-aml** [interpretml/interpret-community#78]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tongyu-microsoft** [comment]
As shown in the pipeline, macOS tests succeeded: https://dev.azure.com/responsibleai/interpret-community/_build?definitionId=77&_a=summary
Note that currently there is some dependency issue causing pipeline failure, but it is not related to macOS issue: https://dev.azure.com/responsibleai/interpret-community/_build/results?buildId=14688&view=results
