### ISSUE TITLE
NB VM dashboard error with jupyter lab selection

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#82]
**Describe the bug**

**To Reproduce**
1. Go to ml.azure.com
2. select explain-regression-local.ipynb
3. select Jupyter-> Jupyter Lab
4. run nb
nb ran until dashboard and then error.

**Expected behavior**
did not expect error

**Screenshots**
![image](https://user-images.githubusercontent.com/6098674/67962142-1164ca00-fbd3-11e9-9aae-ed1911981577.png)

**Desktop (please complete the following information):**
Edge

**Comment by imatiach-msft** [comment]
closing this issue as this is the old widget and I don't believe this issue is relevant anymore
