### ISSUE TITLE
Imports fail on notebook VM

### ISSUE THREAD

**Issue by wamartin-aml** [interpretml/interpret-community#83]
**Describe the bug**
On creation of a new notebook VM, there have been multiple failures to import azureml.contrib, so the dashboard can't be used.

**To Reproduce**
1. Create new notebook VM with default settings
2. Run all for local regression notebook
3. Scroll down to the dashboard section once it's done

Was fixed by importing the dashboard from interpret-community instead.

![Screen Shot 2019-10-31 at 10 37 28 AM](https://user-images.githubusercontent.com/42586848/67965409-5fc89780-fbd8-11e9-8921-28eaf66adf00.png)

**Comment by imatiach-msft** [comment]
@wamartin-aml is the solution here to have better steps in the demo notebook, to tell the user to install the contrib package?

**Comment by imatiach-msft** [comment]
also if this is for the ExplanationClient it probably shouldn't be in this repo

**Comment by imatiach-msft** [comment]
ping @wamartin-aml can this issue be closed now?  Users can use the dashboard from interpret-community instead.

**Comment by wamartin-aml** [comment]
This is no longer a goal of these packages - imports for this dashboard should be coming from interpret-community.
